[workspace]
members = ["wordle", "crossword"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4", features = ["derive"]}
thirtyfour = { version = "0.31"}
tokio = {version = "1"}

[profile.test]
opt-level = 3